# Generated by Django 6.0.5 on 2026-05-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('DOCTOR', 'Doctor behavior'), ('STAFF', 'Staff behavior'), ('WAITING', 'Waiting time'), ('BILLING', 'Billing issue'), ('CLEANLINESS', 'Cleanliness'), ('PHARMACY', 'Pharmacy'), ('OPTICAL', 'Optical'), ('SURGERY', 'Surgery process'), ('CAMP', 'Camp services'), ('CANTEEN', 'Food/canteen'), ('COMMUNICATION', 'Communication issue'), ('SUGGESTION', 'Suggestion/appreciation'), ('EMERGENCY_COMPLAINT', 'Emergency complaint'), ('OTHER', 'Other')], max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('complainant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('complainant_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='complaints/voice/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaints/attachments/')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('ASSIGNED', 'Assigned'), ('ACTION', 'Action Taken'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='NEW', max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
