# Generated by Django 6.0.5 on 2026-05-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_options_complaint_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ind_appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ind_department',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD (Outpatient Department)'), ('IPD', 'Ward / Inpatient Department'), ('Pharmacy', 'Pharmacy counter'), ('Optical', 'Optical counter'), ('Billing', 'Billing / Cash counter'), ('OT', 'Operation Theater (OT) area'), ('Canteen', 'Hospital Canteen'), ('Camp', 'Outreach Camp site'), ('Reception', 'Reception / Help desk'), ('Washroom', 'Washroom / Toilets'), ('Other', 'Other location')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ind_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ind_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_individual_complaint',
            field=models.BooleanField(default=False),
        ),
    ]
