# Generated by Django 6.0.5 on 2026-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_ind_appearance_complaint_ind_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('OPD', 'OPD (Outpatient Department)'), ('IPD', 'Ward / Inpatient Department'), ('Pharmacy', 'Pharmacy counter'), ('Optical', 'Optical counter'), ('Billing', 'Billing / Cash counter'), ('OT', 'Operation Theater (OT) area'), ('Canteen', 'Hospital Canteen'), ('Camp', 'Outreach Camp site'), ('Reception', 'Reception / Help desk'), ('Washroom', 'Washroom / Toilets'), ('Other', 'Other location')], max_length=50)),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('hi', 'Hindi')], default='ne', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rating',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('OPD', 'OPD (Outpatient Department)'), ('IPD', 'Ward / Inpatient Department'), ('Pharmacy', 'Pharmacy counter'), ('Optical', 'Optical Refraction'), ('Billing', 'Billing / Cash counter'), ('OT', 'Operation Theater (OT) area'), ('Canteen', 'Hospital Canteen'), ('Lab & Diagnostics', 'Laboratory & Diagnostics'), ('Reception', 'Reception / Help desk'), ('Other', 'Other location')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ind_department',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD (Outpatient Department)'), ('IPD', 'Ward / Inpatient Department'), ('Pharmacy', 'Pharmacy counter'), ('Optical', 'Optical Refraction'), ('Billing', 'Billing / Cash counter'), ('OT', 'Operation Theater (OT) area'), ('Canteen', 'Hospital Canteen'), ('Lab & Diagnostics', 'Laboratory & Diagnostics'), ('Reception', 'Reception / Help desk'), ('Other', 'Other location')], max_length=50, null=True),
        ),
    ]
