# Generated by Django 6.0.5 on 2026-05-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_rating_remove_complaint_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
    ]
