# Generated by Django 6.0.5 on 2026-05-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_remove_complaint_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Department Complaint',
                'verbose_name_plural': 'Department Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaints.complaint',),
        ),
        migrations.CreateModel(
            name='IndividualComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Individual Complaint',
                'verbose_name_plural': 'Individual Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaints.complaint',),
        ),
        migrations.AlterField(
            model_name='rating',
            name='department',
            field=models.CharField(choices=[('OPD', 'OPD (Outpatient Department)'), ('IPD', 'Ward / Inpatient Department'), ('Pharmacy', 'Pharmacy counter'), ('Optical', 'Optical Refraction'), ('Billing', 'Billing / Cash counter'), ('OT', 'Operation Theater (OT) area'), ('Canteen', 'Hospital Canteen'), ('Lab & Diagnostics', 'Laboratory & Diagnostics'), ('Reception', 'Reception / Help desk'), ('Other', 'Other location')], max_length=50),
        ),
    ]
