# Generated by Django 6.0.5 on 2026-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_proxy_complaint_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRating',
            fields=[
            ],
            options={
                'verbose_name': 'Department Rating',
                'verbose_name_plural': 'Department Ratings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaints.rating',),
        ),
        migrations.CreateModel(
            name='HospitalRating',
            fields=[
            ],
            options={
                'verbose_name': 'Hospital Rating',
                'verbose_name_plural': 'Hospital Ratings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaints.rating',),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_hospital_rating',
            field=models.BooleanField(default=False),
        ),
    ]
