# Generated by Django 6.0.5 on 2026-05-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('hi', 'Hindi')], default='ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('OPD', 'OPD (Outpatient Department)'), ('IPD', 'Ward / Inpatient Department'), ('Pharmacy', 'Pharmacy counter'), ('Optical', 'Optical counter'), ('Billing', 'Billing / Cash counter'), ('OT', 'Operation Theater (OT) area'), ('Canteen', 'Hospital Canteen'), ('Camp', 'Outreach Camp site'), ('Reception', 'Reception / Help desk'), ('Washroom', 'Washroom / Toilets'), ('Other', 'Other location')], max_length=50),
        ),
    ]
